apiVersion: v1
kind: Service
metadata:
  name: mserver-sctp
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver-sctp
  ports:
  - port: 7002
    name: sctp-hostname
    protocol: SCTP
  - port: 7003
    name: sctp-sh
    protocol: SCTP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-sctp-udp
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver-sctp
  ports:
  - port: 7005
    name: udp-hostname
    protocol: UDP
  - port: 7006
    name: udp-sh
    protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-sctp-tcp
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver-sctp
  ports:
  - port: 7008
    name: tcp-hostname
  - port: 7009
    name: tcp-sh
  type: LoadBalancer
