apiVersion: v1
kind: Service
metadata:
  name: tserver
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  #externalTrafficPolicy: Local
  #internalTrafficPolicy: Local
  ports:
  - port: 5001
    name: mconnect
    nodePort: 30001
  - port: 8080
    name: kahttp
    nodePort: 30080
  - port: 8443
    name: kahttps
    nodePort: 30443
