apiVersion: v1
kind: Service
metadata:
  name: tserver-mini
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  type: LoadBalancer
  #allocateLoadBalancerNodePorts: false
  #externalTrafficPolicy: Local
  #internalTrafficPolicy: Local
  ports:
  - port: 5001
  #  name: mconnect
  #- port: 5004
  #  name: nc
