---
apiVersion: v1
kind: Service
metadata:
  name: kahttp-preferdual-lb
spec:
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  selector:
    app: kahttp
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kahttp-ipv4-lb
spec:
  ipFamilies:
  - IPv4
  externalTrafficPolicy: Local
  selector:
    app: kahttp
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kahttp-ipv6-lb
spec:
  ipFamilies:
  - IPv6
  externalTrafficPolicy: Local
  selector:
    app: kahttp
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer
---
