apiVersion: v1
kind: Service
metadata:
  name: mserver-dual-srange
spec:
  loadBalancerSourceRanges:
  - "192.168.1.0/24"
  - "192.168.2.0/24"
  - "fd00::c0a8:100/120"
  - "fd00::c0a8:200/120"
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  type: LoadBalancer
