---
apiVersion: v1
kind: Service
metadata:
  name: mserver-ipv4
spec:
  ipFamilies:
    - IPv4
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-ipv6
spec:
  ipFamilies:
    - IPv6
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-preferdual
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic

