apiVersion: v1
kind: Service
metadata:
  name: mserver-headless-ipv6
spec:
  clusterIP: None
  ipFamilies:
    - IPv6
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-headless-ipv4
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-headless-dual
spec:
  ipFamilyPolicy: PreferDualStack
  clusterIP: None
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
