apiVersion: v1
kind: Service
metadata:
  name: mserver-affinity
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 120
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mserver
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  type: LoadBalancer
