apiVersion: v1
kind: Service
metadata:
  name: mserver-preferdual-lb
spec:
  ipFamilyPolicy: PreferDualStack
  allocateLoadBalancerNodePorts: false
  selector:
    app: mserver-deployment
  loadBalancerClass: Kalle
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-ipv6-lb
spec:
  allocateLoadBalancerNodePorts: false
  ipFamilies:
  - IPv6
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  type: LoadBalancer
  loadBalancerIP: "1000::1"
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-ipv4-lb
spec:
  allocateLoadBalancerNodePorts: false
  ipFamilies:
  - IPv4
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  type: LoadBalancer
  loadBalancerIP: "10.0.0.1"
