#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

f=$GOPATH/src/github.com/Nordix/ctraffic/image/ctraffic
if test -x $f; then
	cp $f $tmp/bin
else
	f=$ARCHIVE/ctraffic.gz
	test -r $f || f=$HOME/Downloads/ctraffic.gz
	test -r $f || die "Not readable [$f]"
	gzip -cd $f > $tmp/bin/ctraffic || die "Failed to uncompress [$f]"
	chmod a+x $tmp/bin/ctraffic
fi

if test -n "$__newver"; then
	mkdir -p $tmp/root
	$dir/k8s-test.sh pack_k8s --dest=$tmp/root --newver=$__newver || die newver
fi

$XCLUSTER install_prog --dest=$tmp host ncat

f=/tmp/$USER/sctpt/sctpt/sctpt
test -x $f && $XCLUSTER install_prog --dest=$tmp $f 

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
