apiVersion: v1
kind: Service
metadata:
  name: mserver-hostnet
spec:
  selector:
    app: mserver-hostnet
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  - port: 5001
    name: mconnect-udp
    protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-headless
spec:
  clusterIP: None
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-no-proxy
  labels:
    service.kubernetes.io/service-proxy-name: none
spec:
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
