apiVersion: apps/v1
kind: Deployment
metadata:
  name: mserver-deployment
spec:
  selector:
    matchLabels:
      app: mserver-deployment
  replicas: 4
  template:
    metadata:
      labels:
        app: mserver-deployment
    spec:
      serviceAccount: default
      containers:
      - name: mserver
        imagePullPolicy: IfNotPresent
        image: registry.nordix.org/cloud-native/mserver:latest
        ports:
        - containerPort: 5001
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-deployment
spec:
  selector:
    app: mserver-deployment
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
