apiVersion: v1
kind: Service
metadata:
  name: tserver-affinity
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 120
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
