apiVersion: v1
kind: Service
metadata:
  name: headless-ipv6
spec:
  clusterIP: None
  ipFamilies:
    - IPv6
  selector:
    app: tserver
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: headless-ipv4
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  selector:
    app: tserver
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  ipFamilyPolicy: RequireDualStack
  clusterIP: None
  selector:
    app: tserver
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
