apiVersion: v1
kind: Service
metadata:
  name: lbrange
spec:
  loadBalancerSourceRanges:
  - "192.168.1.0/24"
  - "192.168.2.0/24"
  - "fd00::192.168.1.0/120"
  - "fd00::192.168.2.0/120"
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  type: LoadBalancer
