---
apiVersion: v1
kind: Service
metadata:
  name: hostnet
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: tserver-hostnet
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: hostnet-ipv4
spec:
  ipFamilies: [ IPv4 ]
  selector:
    app: tserver-hostnet
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: hostnet-ipv6
spec:
  clusterIP: None
  ipFamilies: [ IPv6 ]
  selector:
    app: tserver-hostnet
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
