apiVersion: v1
kind: Pod
metadata:
  name: test-pod-evicted
spec:
  containers:
  - name: alpine
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 10; dd if=/dev/zero of=file bs=1M count=10; sleep 10000"]
    resources:
      limits:
        ephemeral-storage: 5Mi
      requests:
        ephemeral-storage: 5Mi
