apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-app
spec:
  selector:
    matchLabels:
      app: udp-app
  template:
    metadata:
      labels:
        app: udp-app
    spec:
      containers:
      - name: alpine
        imagePullPolicy: IfNotPresent
        image: docker.io/library/alpine:latest
        command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 5005
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: udp-svc
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: udp-app
  ports:
  - port: 5005
    protocol: UDP
    name: nc-udp
  type: NodePort
